#!/bin/sh
set -eu

shell=${SHELL:-/bin/sh}
if [ ! -x "$shell" ]; then
  shell=/bin/sh
fi

exec /usr/bin/gamescope --backend drm --force-windows-fullscreen -- \
  /usr/bin/xterm -wf -hold -fa Monospace -fs 16 -e \
  "$shell" -ic 'exec /usr/bin/hearthdeck'
