//! Embeds the vendored RetroArch joypad autoconfig profiles (see
//! `profiles/udev/README.md`) into the binary as a compile-time constant
//! list, so a Hearthdeck-managed RetroArch install always has controller
//! profiles available no matter how (or whether) the bridge was packaged.
//!
//! The generated module exposes:
//!
//! ```ignore
//! pub const RETROARCH_PROFILES: &[(&str, &str)] = &[("Device.cfg", "contents"), ...];
//! ```

use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR");
    let profiles_dir = Path::new(&manifest_dir).join("profiles").join("udev");

    // Ask cargo to rebuild whenever a vendored profile changes (or one is
    // added/removed), not just when build.rs itself changes.
    println!("cargo:rerun-if-changed={}", profiles_dir.display());

    let mut profiles: Vec<(String, String)> = fs::read_dir(&profiles_dir)
        .unwrap_or_else(|error| {
            panic!(
                "cannot read vendored RetroArch profiles {}: {error}",
                profiles_dir.display()
            )
        })
        .filter_map(|entry| {
            let entry = entry.expect("read_dir entry failed");
            let name = entry.file_name();
            let name = name.to_str().expect("profile filename is not UTF-8");
            // Skip the attribution README and anything else that is not a profile.
            if !name.ends_with(".cfg") {
                return None;
            }
            let contents = fs::read_to_string(entry.path())
                .unwrap_or_else(|error| panic!("cannot read {name}: {error}"));
            Some((name.to_owned(), contents))
        })
        .collect();
    // Deterministic order for reproducible binaries.
    profiles.sort_by(|left, right| left.0.cmp(&right.0));

    let mut generated = String::from(
        "// Generated by build.rs from services/hearthdeck-bridge/profiles/udev. \
         Do not edit by hand.\n\n",
    );
    generated.push_str("pub const RETROARCH_PROFILES: &[(&str, &str)] = &[\n");
    for (name, contents) in &profiles {
        // `{:?}` produces a valid, fully-escaped Rust string literal.
        generated.push_str(&format!("    ({name:?}, {contents:?}),\n"));
    }
    generated.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("cargo sets OUT_DIR");
    fs::write(Path::new(&out_dir).join("retro_profiles.rs"), generated)
        .expect("cannot write generated retro_profiles.rs");
}
